sea_ice <- read.table("sea_ice_data.txt",header=T)
res1= lm(Arctic_Sea_Ice_Extent~Year,data=sea_ice)
plot(sea_ice)
abline(res1)
plot(sea_ice[1:34,1],studres(res1),ylab='Studentized Residuals',xlab="Year")
resNL= lm(Arctic_Sea_Ice_Extent~Year+I(Year^2),data=sea_ice)
vec= seq(sea_ice[1,1],sea_ice[34,1],by=0.1)
lines(vec,resNL$coefficients[1]+resNL$coefficients[2]*vec+resNL$coefficients[3]*vec^2)
anova(res1,resNL)