endur= read.csv("fake.txt",header=T,sep=",")
plot(endur$endurance~endur$age,main="Scatterplot",ylab="Endurance",xlab="Age")
abline(lm(endur$endurance~endur$age),col="blue")
plot(endur$endurance~endur$activeyears,main="Scatterplot",ylab="Endurance",xlab="Active Years")
abline(lm(endur$endurance~endur$activeyears),col="green")
model1= lm(endur$endurance~endur$age)
summary(model1)
model2= lm(endur$endurance~endur$activeyears)
summary(model2)
model3= lm(endur$endurance~endur$age + endur$activeyears)
summary(model3)